"""empty message

Revision ID: 344990269bb8
Revises: d696c8c4d987
Create Date: 2020-07-23 23:11:11.681368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344990269bb8'
down_revision = 'd696c8c4d987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
