"""empty message

Revision ID: 8ec0f0a8d9eb
Revises: 344990269bb8
Create Date: 2020-07-25 19:26:02.622412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec0f0a8d9eb'
down_revision = '344990269bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'todolists', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todolists', type_='unique')
    # ### end Alembic commands ###
