"""empty message

Revision ID: b4c827765ed9
Revises: 7c53cd954910
Create Date: 2020-07-16 17:20:11.649087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c827765ed9'
down_revision = '7c53cd954910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    
    # updating existing records for having completed value as False. We enter a SQL string.
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    
    # again putting constraint on completed column as nullable = False.
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
